name: "Build"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: extension
          filename: "{name}-{version}.xpi"
#       - name: "Upload Artifact"
#         uses: actions/upload-artifact@v3
#         with:
#           path: *.xpi
#       - name: Generate release tag
#         id: tag
#         run: |
#           echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test1
          files: *.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
